import DesktopNav from "./components/DesktopNav";
import MobileNav from "./components/MobileNav";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div className="mobile-only">
          <MobileNav />
        </div>
        <div className="desktop-only">
          <DesktopNav />
        </div>
        <main className="main-content">
          {children}
        </main>
      </body>
    </html>
  );
}
